SELECT D1.ID, IF(CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA D1 LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM  ECOLI_DATA 
    GROUP BY PARENT_ID) D2
ON (D1.ID = D2.PARENT_ID);
