SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM   (SELECT *
        FROM USED_GOODS_BOARD
        WHERE STATUS = "DONE") A
JOIN   USED_GOODS_USER B
ON     A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES 

